import { v4 as uuid } from 'uuid';

const sampleUserId = 'gXRwqvhT';
const now = new Date();

export const mockExpenses = [
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 1500,
		amountUsd: 0,
		exchangeRate: 1200,
		currency: 'ARS',
		categoryId: 'food',
		subCategoryId: 'groceries',
		note: 'Verduras en el chino',
		date: new Date('2024-07-01'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 0,
		amountUsd: 5,
		exchangeRate: 1300,
		currency: 'USD',
		categoryId: 'subscriptions',
		note: 'Netflix',
		date: new Date('2024-07-03'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 3500,
		amountUsd: 0,
		exchangeRate: 1250,
		currency: 'ARS',
		categoryId: 'transport',
		subCategoryId: 'uber',
		note: 'Viaje a reunión',
		date: new Date('2024-07-05'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 8000,
		amountUsd: 0,
		exchangeRate: 1270,
		currency: 'ARS',
		categoryId: 'health',
		note: 'Compra de medicamentos',
		date: new Date('2024-07-06'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 0,
		amountUsd: 20,
		exchangeRate: 1290,
		currency: 'USD',
		categoryId: 'technology',
		note: 'Licencia de software',
		date: new Date('2024-07-08'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 2100,
		amountUsd: 0,
		exchangeRate: 1220,
		currency: 'ARS',
		categoryId: 'food',
		subCategoryId: 'delivery',
		note: 'Empanadas el viernes',
		date: new Date('2024-07-09'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 4000,
		amountUsd: 0,
		exchangeRate: 1250,
		currency: 'ARS',
		categoryId: 'entertainment',
		note: 'Entrada al cine',
		date: new Date('2024-07-10'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 0,
		amountUsd: 12,
		exchangeRate: 1260,
		currency: 'USD',
		categoryId: 'subscriptions',
		note: 'Spotify Premium',
		date: new Date('2024-07-11'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 950,
		amountUsd: 0,
		exchangeRate: 1240,
		currency: 'ARS',
		categoryId: 'personal-care',
		note: 'Corte de pelo',
		date: new Date('2024-07-12'),
		createdAt: now,
	},
	{
		id: uuid(),
		userId: sampleUserId,
		amountArs: 12000,
		amountUsd: 0,
		exchangeRate: 1280,
		currency: 'ARS',
		categoryId: 'home',
		note: 'Reparación de estufa',
		date: new Date('2024-07-13'),
		createdAt: now,
	},
] as const;

export function getRandomExpense() {
	return mockExpenses[
		Math.floor(Math.random() * mockExpenses.length)
	] as (typeof mockExpenses)[number];
}
