/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as IndexImport } from './pages/index'

// Create Virtual Routes

const SignInIndexLazyImport = createFileRoute('/sign-in/')()
const SignInCallbackLazyImport = createFileRoute('/sign-in/callback')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignInIndexLazyRoute = SignInIndexLazyImport.update({
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/sign-in/index.lazy').then((d) => d.Route))

const SignInCallbackLazyRoute = SignInCallbackLazyImport.update({
  path: '/sign-in/callback',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./pages/sign-in/callback.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sign-in/callback': {
      preLoaderRoute: typeof SignInCallbackLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in/': {
      preLoaderRoute: typeof SignInIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SignInCallbackLazyRoute,
  SignInIndexLazyRoute,
])

/* prettier-ignore-end */
